### ISSUE TITLE
Interface arrays passed with no size information

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/lib_device_control#60]
Multiple API functions have an array of interfaces included in the arguments. However, this array is not sized and this generates warnings. A major version update is needed to fix this.

**Comment by larry-xmos** [comment]
The interface array length is the number of threads controlled. It should be ok to use an unknown length array because length will be passed in a hidden argument at the end, and used in compiler-generated boundary check.

Close the issue now since XVF3510 does not suffer from these warnings
